apiVersion: rbac.authorization.k8s.io/v1beta1
kind: 
metadata:
labels:
    component: helm
name: helm
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: cluster-admin
subjects:
- kind: ServiceAccount
name: helm
namespace: helm
